### ISSUE TITLE
A bit more steps in documentation

### ISSUE THREAD

**Issue by shadow-identity** [sbwml/luci-app-qbittorrent#1]
Hi! 
Thanks for doing this work.
I'm trying to build it right on my openWRT router.
What I did: 

1. create a user
2.  install `git`, `git-http` and `make` packages
3.  `git clone` your repo
4.  `cd` into a cloned folder
5.  `$ make menuconfig` according to the README.md, then I have this error:
```
gg@OpenWrt:~/openwrt-qBittorrent$ make menuconfig
make: *** No rule to make target 'menuconfig'.  Stop.
```
I noticed that there is no `Makefile` in the root folder of the project, so I tried to `cd` into subfolders and try `make menuconfig` there, without success. I'm not experienced in making packages, so I can miss something simple :(

Could you please let me know what I miss? I'll do these steps and will update your documentation after.
Thanks!

**Comment by sbwml** [comment]
No, it needs to be compiled from the openwrt source, you can use the openwrt sdk to build, and finally you will get the qbittorrent (ipk) package.

https://openwrt.org/docs/guide-developer/toolchain/using_the_sdk#usage
