### ISSUE TITLE
有打算更新到4.6.0吗？

### ISSUE THREAD

**Issue by science2468** [sbwml/luci-app-qbittorrent#2]
我缝合失败了。改了qt6base、qt6tools、qbittorrent3者的Makefile中的版本和hash，其他没改，编译出错。少了libdeflate-gzip。

**Comment by sbwml** [comment]
已更新

**Comment by science2468** [comment]
![图片](https://github.com/sbwml/luci-app-qbittorrent/assets/102643084/783ef7eb-ea53-4ebb-9258-b4cbe0da5d7a)
崩溃了。这是不是要去更改下qbittorrent的配置文件啊？
好像是依赖的问题，我去把编译出来的依赖也安装进去。

**Comment by sbwml** [comment]
不知道   我还没用过   每天回家再看看

**Comment by science2468** [comment]
> 不知道 我还没用过 每天回家再看看

解决了，是依赖的问题。因为把luci都卸载了，只启动qbittorrent报错

> Error relocating /usr/bin/qbittorrent-nox: _ZN14QReadWriteLock14tryLockForReadE14QDeadlineTimer: symbol not found
Error relocating /usr/bin/qbittorrent-nox: _ZTVN9QRunnable16QGenericRunnableE: symbol not found
Error relocating /usr/bin/qbittorrent-nox: _ZN9QRunnable16warnNullCallableEv: symbol not found
Error relocating /usr/bin/qbittorrent-nox: _ZN8QVariant13moveConstructE9QMetaTypePv: symbol not found
Error relocating /usr/bin/qbittorrent-nox: _ZNK20QXmlStreamAttributes5valueE14QAnyStringView: symbol not found
Error relocating /usr/bin/qbittorrent-nox: _ZN14QReadWriteLock15tryLockForWriteE14QDeadlineTimer: symbol not found
Error relocating /usr/bin/qbittorrent-nox: _ZN14QReadWriteLock16destroyRecursiveEP21QReadWriteLockPrivate: symbol not found

我就把qbittorrent卸载重新装了编译下来的依赖，解决了。
现在已经正常启动了。
