### ISSUE TITLE
Please change default lang to `en`

### ISSUE THREAD

**Issue by remittor** [sbwml/luci-app-qbittorrent#3]
Please change default lang to `en`: https://github.com/sbwml/luci-app-qbittorrent/blob/7de00eebcca1c169715c834167128b979b277b6e/luci-app-qbittorrent/root/etc/qbittorrent/qBittorrent.conf.example#L30

Your project was added to https://github.com/fantastic-packages/packages/commit/cddbf857c5251655f330d1ef01a543d28455c677

**Comment by sbwml** [comment]
[sbwml/luci-app-qbittorrent](https://github.com/sbwml/luci-app-qbittorrent) 存在的目的仅为了我自己构建 openwrt 时将其内置于固件中，而我需要的是简体中文。🙂
