### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by Alexey71** [sbwml/luci-app-qbittorrent#4]
Hi. Unauthorized error appears when trying to open the web interface from openwrt. If you open it manually, it opens normally. How fix?

![2024-08-05_000700](https://github.com/user-attachments/assets/8134e1af-d375-4a6c-beb2-fddb45a1c449)
![2024-08-05_000723](https://github.com/user-attachments/assets/37c25547-c45c-44c4-9d64-999a26426fbd)

**Comment by Alexey71** [comment]
Sorry. config fixed

**Comment by shadow-identity** [comment]
@Alexey71 Could you tell what was the mistake and what was the fix?

**Comment by Alexey71** [comment]
@shadow-identity Disable "Enable Cross-Site Request Forgery (CSRF) protection"

![2024-08-05_145633](https://github.com/user-attachments/assets/60caf478-465f-432e-9111-d0040ff28360)
